select *
from customer
limit 5;

--Q1. What is the total revenue generated by male vs. female customers?
select 
		gender,
		sum(purchase_amount) as revenue
from customer
group by gender;

--Q2. Which customers used a discount but still spent more than the average purchase amount?
select
		customer_id,
		purchase_amount
from customer
where discount_applied = 'Yes'
	  and purchase_amount >= (select avg(purchase_amount) from customer);

--Q3. Which are the top 5 products with the highest average review rating?
select 
	  item_purchased,
	  round(avg(review_rating::numeric),2) as "Average review rating"
	  -- for postgre alias name has to be given in double " and not on single '
from customer
group by item_purchased
order by avg(review_rating) desc
limit 5;

--Q4. Compare the average Purchase Amounts between Standard and Express Shipping.
select 
		shipping_type,
		round(avg(purchase_amount),2)
from customer
where shipping_type in ('Standard','Express')
group by shipping_type;

--Q5. Do subscribed customers spend more? Compare average spend and total revenue between subscribers and non-subscribers.
select 
		subscription_status,
		count(customer_id) as total_customer,
		round(avg(purchase_amount),2) as avg_spend,
		round(sum(purchase_amount),2) as total_revenue
from customer
group by subscription_status
order by total_revenue, avg_spend desc;

--Q6. Which 5 products have the highest percentage of purchases with discounts applied?
--Q7. Segment customers into New, Returning, and Loyal based on their total number of previous purchases, and show the count of each segment.
--Q8. What are the top 3 most purchased products within each category?
--Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
--Q10. What is the revenue contribution of each age group?